import re

abbreviation_dict = {
    "#": "broken bone (fracture)",
    "A&E": "accident and emergency",
    "a.c.": "before meals",
    "a.m.": "morning",
    "AF": "atrial fibrillation",
    "AMHP": "approved mental health professional",
    "APTT": "activated partial thromboplastin time",
    "ASQ": "Ages and Stages Questionnaire",
    "b.d.s": "2 times a day",
    "b.i.d.": "twice a day",
    "BMI": "body mass index",
    "BNO": "bowels not open",
    "BO": "bowels open",
    "BP": "blood pressure",
    "c/c": "chief complaint",
    "CMHN": "community mental health nurse",
    "CPN": "community psychiatric nurse",
    "CSF": "cerebrospinal fluid",
    "CSU": "catheter stream urine sample",
    "CT scan": "computerised tomography scan",
    "CVP": "central venous pressure",
    "CXR": "chest X-ray",
    "DNACPR": "do not attempt cardiopulmonary resuscitation",
    "DNAR": "do not attempt resuscitation",
    "DNR": "do not resuscitate",
    "Dr": "doctor",
    "DVT": "deep vein thrombosis",
    "Dx": "diagnosis",
    "ECG": "electrocardiogram",
    "ED": "emergency department",
    "EEG": "electroencephalogram",
    "EMU": "early morning urine sample",
    "ESR": "erythrocyte sedimentation rate",
    "EUA": "examination under anaesthetic",
    "FBC": "full blood count",
    "FOBT": "faecal occult blood test",
    "FIT": "faecal immunochemical test",
    "FY1": "foundation year 1 doctor",
    "FY2": "foundation year 2 doctor",
    "GA": "general anaesthetic",
    "gtt.": "drop(s)",
    "h.": "hour",
    "h/o": "history of",
    "Hb": "haemoglobin",
    "HCA": "healthcare assistant",
    "HCSW": "healthcare support worker",
    "HDL": "high-density lipoprotein",
    "HRT": "hormone replacement therapy",
    "Ht": "height",
    "Hx": "history",
    "i": "1 tablet",
    "ii": "2 tablets",
    "iii": "3 tablets",
    "i.m.": "injection into a muscle",
    "i.v.": "injection directly to a vein",
    "INR": "international normalised ratio",
    "IVI": "intravenous infusion",
    "IVP": "intravenous pyelogram",
    "Ix": "investigations",
    "LA": "local anaesthetic",
    "LDL": "low-density lipoprotein",
    "LFT": "liver function test",
    "LMP": "last menstrual period",
    "M/R": "modified release",
    "MRI": "magnetic resonance imaging",
    "MRSA": "methicillin-resistant Staphylococcus aureus",
    "MSU": "mid-stream urine sample",
    "n.p.o.": "nothing by mouth",
    "NAD": "nothing abnormal discovered",
    "NAI": "non-accidental injury",
    "NBM": "nil by mouth",
    "NG": "nasogastric",
    "nocte": "every night",
    "NoF": "neck of femur",
    "NSAID": "non-steroidal anti-inflammatory drug",
    "o.d.": "once a day",
    "o/e": "on examination",
    "OT": "occupational therapist",
    "p.c.": "after food",
    "p.m.": "afternoon or evening",
    "p.o.": "orally",
    "POD": "podiatrist",
    "p.r.": "rectally",
    "p.r.n.": "as needed"
}

def expand_abbreviations(text, abbr_dict):
    for abbr, full in abbr_dict.items():
        pattern = r'\b' + re.escape(abbr) + r'\b'
        text = re.sub(pattern, full, text)
    return text

def replace_synonyms(text, synonyms):
    for k, v in synonyms.items():
        pattern = r'\b' + re.escape(k) + r'\b'
        text = re.sub(pattern, v, text, flags=re.IGNORECASE)
    return text